### ISSUE TITLE
Compilation error with Intel's compiler on Windows

### ISSUE THREAD

**Issue by gfursin** [dividiti/gemmbench#1]
I am trying to compile gemmbench-cl-launcher-1.0 on Windows using ICC 2015 and get the following errors (related to C++):

D:\Work1\CK\ck-repos\dividiti-gemmbench\program\gemmbench-cl-launcher-1.0\tmp>call D:\Work1\CK\ck-repos\fgg-local-win\env\289842d618a4e54a\env.bat
Intel(R) Parallel Studio XE 2015
Copyright (C) 1985-2014 Intel Corporation. All rights reserved.
Intel(R) Parallel Studio XE 2015 Update 1 Composer Edition (package 148)

---

Detected compiler version: 15.0.1.148

---

Compiler vars:
  XOPENME=1

---

Executing prepared batch file tmp-t0enb1.bat ...
Intel(R) Parallel Studio XE 2015
Copyright (C) 1985-2014 Intel Corporation. All rights reserved.
Intel(R) Parallel Studio XE 2015 Update 1 Composer Edition (package 148)

Intel(R) Parallel Studio XE 2015
Copyright (C) 1985-2014 Intel Corporation. All rights reserved.
Intel(R) Parallel Studio XE 2015 Update 1 Composer Edition (package 148)

icl /c /DWINDOWS /GS- /MD /I..\ /DXOPENME=1  /I"C:\Program Files (x86)\Intel\OpenCL SDK\4.6\include" /I"D:!FGG\Installations\lib-cjson-2013-icc-2015-windows-64
\include" /I"D:!FGG\Installations\lib-rtl-xopenme-0.3-llvm-3.6.0-windows-64\include"  ..\cl_state.cpp  /Fecl_state.obj
Intel(R) C++ Intel(R) 64 Compiler XE for applications running on Intel(R) 64, Version 15.0.1.148 Build 20141023
Copyright (C) 1985-2014 Intel Corporation.  All rights reserved.

cl_state.cpp
..\cl_state.hpp(576): warning #1478: function "clCreateCommandQueue" (declared at line 1358 of "C:\Program Files (x86)\Intel\OpenCL SDK\4.6\include\CL/cl.h") wa
s declared deprecated
          queue = clCreateCommandQueue(context, device, properties, &err);
                  ^

D:\Work1\CK\ck-repos\dividiti-gemmbench\program\gemmbench-cl-launcher-1.0\cl_dataset.hpp(63): error: a member of type "const cl_float={float}" cannot have an in
-class initializer
      const static T range = static_cast<T>(1);
                           ^
          detected during:
            instantiation of class "gemmbench::dataset<T> [with T=cl_float={float}]" at line 792 of "..\cl_state.hpp"
            instantiation of "void gemmbench::state::_execute_kernel<T>() [with T=cl_float={float}]" at line 817 of "..\cl_state.hpp"

D:\Work1\CK\ck-repos\dividiti-gemmbench\program\gemmbench-cl-launcher-1.0\cl_dataset.hpp(63): error: a member of type "const cl_double={double}" cannot have an
in-class initializer
      const static T range = static_cast<T>(1);
                           ^
          detected during:
            instantiation of class "gemmbench::dataset<T> [with T=cl_double={double}]" at line 792 of "..\cl_state.hpp"
            instantiation of "void gemmbench::state::_execute_kernel<T>() [with T=cl_double={double}]" at line 821 of "..\cl_state.hpp"

compilation aborted for ..\cl_state.cpp (code 2)

---

Compilation time: 3.040 sec.; Object size: 0; MD5:
Warning: compilation failed!

By the way, I generally think that it's easier to use C instead of C++ for such simple benchmarks - it will make them much more portable ...

**Comment by psyhtest** [comment]
Thanks for reporting this Grigori!

Clang 3.7 gives a more insightful diagnostic:

```
$ clang++ -c   -I../ -DXOPENME=1 -mfloat-abi=hard -I/home/anton/CK/ck-tools/lib-cjson-2013-gcc-local-linux-32/include -I/home/anton/CK/ck-tools/lib-rtl-xopenme-0.3-gcc-local-linux-32/include -I/usr/include  ../cl_state.cpp  -o cl_state.o
In file included from ../cl_state.cpp:4:
In file included from ../cl_state.hpp:7:
../cl_dataset.hpp:63:20: warning: in-class initializer for static data member of type 'const float' is a GNU extension [-Wgnu-static-float-init]
    const static T range = static_cast<T>(1);
                   ^       ~~~~~~~~~~~~~~~~~
../cl_state.hpp:792:31: note: in instantiation of template class 'gemmbench::dataset<float>' requested here
        gemmbench::dataset<T> data(args.matrix_order);
                              ^
../cl_state.hpp:817:13: note: in instantiation of function template specialization 'gemmbench::state::_execute_kernel<float>' requested here
            _execute_kernel<cl_float>();
            ^
In file included from ../cl_state.cpp:4:
In file included from ../cl_state.hpp:7:
../cl_dataset.hpp:63:20: warning: in-class initializer for static data member of type 'const double' is a GNU extension [-Wgnu-static-float-init]
    const static T range = static_cast<T>(1);
                   ^       ~~~~~~~~~~~~~~~~~
../cl_state.hpp:792:31: note: in instantiation of template class 'gemmbench::dataset<double>' requested here
        gemmbench::dataset<T> data(args.matrix_order);
                              ^
../cl_state.hpp:821:13: note: in instantiation of function template specialization 'gemmbench::state::_execute_kernel<double>' requested here
            _execute_kernel<cl_double>();
            ^
2 warnings generated.
```

It's one of those C++ gotchas where only _integral_ static class members can have initialisers inside a class declaration, but not _floating-point_ (e.g. see [here](http://stackoverflow.com/questions/2454019/why-arent-static-const-floats-allowed)).

In this case, using a static floating-point constant could be avoided altogether by using default function arguments. I have now done this for this and two other (integral) cases. `clang++` is now happy. Could you please verify the Intel compiler is happy too?

**Comment by psyhtest** [comment]
> By the way, I generally think that it's easier to use C instead of C++ 
> for such simple benchmarks - it will make them much more portable ...

This benchmark potentially requires 4 different floating-point data types: single-precision (S), double-precision (D), complex single-precision (C) and complex double-precision (Z). It's a classical case for using C++ function templates. Alternatives would be using conditional compilation with macros or code duplication. (Which of the alternatives is worse is almost up to a personal taste.)

I have tried to avoid relying on C++ bindings for OpenCL. In my experience, they do cause trouble across vendor implementations.

**Comment by psyhtest** [comment]
This other warning is interesting:

```
cl_state.cpp
..\cl_state.hpp(576): warning #1478: function "clCreateCommandQueue" (declared at line 1358 of "C:\Program Files (x86)\Intel\OpenCL SDK\4.6\include\CL/cl.h") wa
s declared deprecated
queue = clCreateCommandQueue(context, device, properties, &err);
^
```

Apparently, `clCreateCommandQueue()` is deprecated in OpenCL 2.0. I have opened an [enhancement ticket](https://github.com/dividiti/gemmbench/issues/2) to support `clCreateCommandQueueWithProperties()`.

**Comment by gfursin** [comment]
Thanks, Anton! There was another issue that I fixed (#include <algorithm>) and now it is compiled on Windows both with ICC and Microsoft Compiler ... I close this ticket!
